// Generated by CoffeeScript 1.10.0
(function() {
  var coffee, cssmin, ecstatic, gulp, gutil, http, less, shell, uglify;

  gulp = require('gulp');

  coffee = require('gulp-coffee');

  cssmin = require('gulp-cssmin');

  ecstatic = require('ecstatic');

  gutil = require('gulp-util');

  http = require('http');

  less = require('gulp-less');

  shell = require('gulp-shell');

  uglify = require('gulp-uglifyjs');

  gulp.task('coffee', function() {
    return gulp.src('src/scripts/*.coffee').pipe(coffee({
      bare: true
    }).on('error', gutil.log)).pipe(gulp.dest('src/scripts/'));
  });

  gulp.task('less', function() {
    return gulp.src('src/styles/*.less').pipe(less({
      compress: true
    })).pipe(gulp.dest('src/styles/'));
  });

  gulp.task('uglify', function() {
    return gulp.src('dist/slick-lightbox.js').pipe(uglify('slick-lightbox.min.js', {
      outSourceMap: true
    })).pipe(gulp.dest('dist/'));
  });

  gulp.task('coffeedoc', shell.task(['coffeedoc src/scripts/slick-lightbox.coffee']));

  gulp.task('buildGHPages', shell.task(['jade index.jade']));

  gulp.task('watch', function() {
    gulp.watch('src/scripts/*.coffee', ['coffee']);
    gulp.watch('src/styles/*.less', ['less']);
    return gulp.watch(['index.jade', 'README.md'], ['buildGHPages']);
  });

  gulp.task('preBuild', ['coffee', 'less'], function() {
    return gulp.src(['src/styles/slick-lightbox.css', 'src/scripts/slick-lightbox.js']).pipe(gulp.dest('dist/'));
  });

  gulp.task('build', ['preBuild'], function() {
    return gulp.start('uglify', 'coffeedoc', 'buildGHPages');
  });

  gulp.task('server', function() {
    gulp.start('coffee', 'less', 'watch');
    return http.createServer(ecstatic({
      root: __dirname
    })).listen(9000);
  });

  gulp.task('default', function() {
    return gulp.start('server');
  });

}).call(this);
